language: node_js
node_js:
  - 0.10

env:
  global:
    - SAUCE_USERNAME=angular-ci
    - SAUCE_ACCESS_KEY=78924453-3ea4-4aa8-acbf-8ff434f889b9
    - SAUCE_CONNECT_READY_FILE=/tmp/sauce-connect-ready

script:
  - ./lib/sauce/sauce_connect_setup.sh
  - npm install -g grunt-cli
  - grunt ci-checks package
  - ./lib/sauce/sauce_connect_block.sh
  - grunt parallel:travis --reporters dots --browsers SL_Chrome
